spdk25.09 patch

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -134,6 +134,8 @@ function usage() {
 	echo " --without-golang          No path required."
 	echo " --with-aio-fsdev          Build aio FSDEV component."
 	echo " --without-aio-fsdev       No path required."
+	echo " --with-ssam               Support to build ssam for DPU storage accel."
+	echo " --without-ssam            No path required."
 	echo ""
 	echo "Environment variables:"
 	echo ""
@@ -622,6 +624,15 @@ for i in "$@"; do
 			;;
 		--without-fsdev)
 			CONFIG[FSDEV]=n
+			;;
+		--with-ssam)
+			CONFIG[SSAM]=y
+			;;
+		--without-ssam)
+			CONFIG[SSAM]=n
+			;;
+        --with-ssam-only)
+			CONFIG[SSAM_ONLY]=y
 			;;
 		--with-nvme-cuse)
 			CONFIG[NVME_CUSE]=y
@@ -1363,6 +1374,13 @@ if [[ "${CONFIG[AIO_FSDEV]}" = "y" ]]; then
 		CONFIG[HAVE_STRUCT_STAT_ST_ATIM]=n
 		CONFIG[HAVE_STRUCT_STAT_ST_ATIMESPEC]=n
 	fi
+fi
+
+if [[ "${CONFIG[SSAM_ONLY]}" = "y" ]]; then
+    if [[ "${CONFIG[SSAM]}" = "n" ]]; then
+        echo "--with-ssam-only requires --with-ssam."
+        exit 1
+    fi
 fi
 
 # For ARM Neoverse-N1 platform, debug build needs gcc version newer than 8.4
